#!/usr/bin/env bash
# Hash every trained-artifact file under models/ and write models/CHECKSUMS.txt (V1F-04).
# Safe to re-run; overwrites the output file. Requires bash 4+ or a POSIX sh with find.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MODELS="${ROOT}/models"
OUT="${MODELS}/CHECKSUMS.txt"
DATE_UTC="${DATE_UTC:-$(date -u +%Y-%m-%d)}"
RUN_ID="${RUN_ID:-${GITHUB_SHA:-local}}"

mkdir -p "${MODELS}"
{
  echo "# Auto-generated by scripts/hash_models.sh — one line per file."
  echo "# Format: <sha256> <filename> <date_utc> <run_id>"
} > "${OUT}.tmp"

_sh256() {
  local f="$1"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$f" | awk '{print $1}'
  else
    shasum -a 256 "$f" | awk '{print $1}'
  fi
}

if [[ -d "${MODELS}" ]]; then
  while IFS= read -r -d '' f; do
    base="$(basename "$f")"
    sum="$(_sh256 "$f")"
    echo "${sum}  ${base}  ${DATE_UTC}  ${RUN_ID}" >> "${OUT}.tmp"
  done < <(find "${MODELS}" -type f \( -name "*.pth" -o -name "*.p" -o -name "*.pkl" \) -print0 2>/dev/null || true)
fi

mv "${OUT}.tmp" "${OUT}"
echo "Wrote ${OUT}"
